### ISSUE TITLE
Android - Problem 

### ISSUE THREAD

**Issue by vadermemo** [bberak/react-native-donkey-kong#1]
Hi friends,

  I used your code on iOS and all is working fine, but when I tried on Android device the  behaviour is not the same than iOS, the Mario´s movements have issues and is impossible to play.

where is source to handle the timing to make the player´s movements ?

Best regards.

**Comment by bberak** [comment]
Hi @vadermemo,

Thanks for pointing this out.. I don't have a physical Android device - so I've just been playing the game on a simulator, and it seemed playable (although the GIF rendering is a little strange).

That said, the player's left/right/jump movements are handled by the platforms system: https://github.com/bberak/react-native-donkey-kong/blob/master/src/systems/platforms.js

And the climbing movements are handled by the ladders system: https://github.com/bberak/react-native-donkey-kong/blob/master/src/systems/ladders.js

Let me know if happen to stumble upon the problem, and of course - a PR would always be welcome 🙌

Cheers!

**Comment by dcp12345678** [comment]
Really nice job with this, thanks for making the project. Do you have any instructions on how to navigate Mario? I'm just using simulator and it seems left mouse click makes Mario jump, but I'm having trouble seeing how to move him right, left, up and down.

**Comment by bberak** [comment]
Thanks @dcp12345678, appreciate it!

You should be able to move left/right by swiping left/right. Jump is swipe up or tap (if you're near the bottom of a ladder Mario will get on it and start climbing). If you're near the top of a ladder and swipe down, Mario will descend the ladder.

The idea is to be able to navigate up the level using a single thumb. Let me know if you have any issues :)
